### ISSUE TITLE
bugs (?) mod defrag and auto-downloading

### ISSUE THREAD

**Issue by kompowiec** [OpenArena/leixperimental#7]
I don't know whether this is a good place to report such errors, i think it would be appropriate. 
I noticed 2 bug, which extremely pissed off.

First this error concerns mod defrag - every change maps cause caption "connecting interputted" although I have a good internet connection. Afther reset, turn search server and played, later is nextmap and here we go again and again.

second error it problem with auto-downloading - if for some reason, download will be aborted, it then switch search servers it disappear almost all servers, show only several. Afther reset game is fine (until it does not happen again.)

**Comment by leilei-** [comment]
nothing to do with OA3.
